# Generated by Django 3.2 on 2021-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('column_separator', models.IntegerField(blank=True, null=True)),
                ('string_character', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('field_type', models.IntegerField(choices=[(1, 'Full name'), (2, 'Job'), (3, 'Email'), (4, 'Domain name'), (6, 'Company name'), (7, 'Text'), (5, 'Phone number'), (8, 'Integer'), (9, 'Address'), (10, 'Date')])),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
