# Generated by Django 3.2 on 2021-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0003_auto_20210421_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
