# Generated by Django 3.2 on 2021-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0004_auto_20210421_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='row_number',
            field=models.IntegerField(null=True),
        ),
    ]
