# Generated by Django 3.2 on 2021-04-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0005_schema_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafield',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_generator.schema'),
        ),
    ]
