# Generated by Django 3.2 on 2021-04-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0006_schemafield_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema_fields', to='data_generator.schema'),
        ),
    ]
