# Generated by Django 3.2 on 2021-04-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0008_auto_20210423_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemafield',
            name='field_type',
            field=models.CharField(choices=[('full_name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('domain_name', 'Domain name'), ('company_name', 'Company name'), ('text', 'Text'), ('phone_number', 'Phone number'), ('integer', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=256),
        ),
    ]
