# Generated by Django 3.2 on 2021-04-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0009_alter_schemafield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), (' ', 'Space ( )'), ('|', 'Pipe (|)')], default=',', max_length=256),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(blank=True, choices=[('"', 'Double quotes (")'), ("'", "Single quote (') ")], default='"', max_length=256),
        ),
    ]
