# Generated by Django 3.2 on 2021-04-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0010_auto_20210424_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemafield',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemafield',
            name='max_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemafield',
            name='min_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemafield',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemafield',
            name='text_len',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
