# Generated by Django 3.2 on 2021-04-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0013_remove_schema_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='path',
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_csv',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=''),
        ),
    ]
