# Generated by Django 3.2 on 2021-05-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0014_auto_20210430_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='file_csv',
        ),
        migrations.AddField(
            model_name='dataset',
            name='path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
